In [1]:
import pandas as pd

In [6]:
df = pd.read_parquet('data/raw/ABT.parquet')

In [7]:
df.head()

,Date,Close,High,Low,Open,Volume,ticker,vix,tnx,xlf,xlk,xle,event_timestamp
0,2021-05-03,108.812706,109.841392,108.494089,109.741255,4917600,ABT,18.309999,1.607,33.399250,67.045975,21.090748,2021-05-03 00:00:00+00:00
1,2021-05-04,107.001114,108.594205,105.990638,108.512271,9221800,ABT,19.480000,1.592,33.665054,65.842804,21.103216,2021-05-04 00:00:00+00:00
2,2021-05-05,107.884125,108.211847,106.673374,107.237786,5632400,ABT,19.150000,1.584,33.940018,65.683968,21.784771,2021-05-05 00:00:00+00:00
3,2021-05-06,108.139030,108.220958,106.236421,107.465382,4305300,ABT,18.389999,1.561,34.444130,66.343315,21.896978,2021-05-06 00:00:00+00:00
4,2021-05-07,108.284691,109.622889,108.111731,109.031168,4076600,ABT,16.690001,1.577,34.627441,66.911209,22.287622,2021-05-07 00:00:00+00:00

In [4]:
df1 = pd.read_parquet('data/raw/ABBV.parquet')
df1.head()

,Date,Close,High,Low,Open,Volume,ticker,vix,tnx,xlf,xlk,xle,event_timestamp
0,2021-05-03,95.072311,95.420499,92.510628,93.182141,9138200,ABBV,18.309999,1.607,33.399261,67.045967,21.090748,2021-05-03 00:00:00+00:00
1,2021-05-04,94.425667,96.116874,93.720999,95.022564,8151400,ABBV,19.480000,1.592,33.665058,65.842796,21.103216,2021-05-04 00:00:00+00:00
2,2021-05-05,95.984230,96.398741,94.467117,94.765566,7021400,ABBV,19.150000,1.584,33.940014,65.683998,21.784771,2021-05-05 00:00:00+00:00
3,2021-05-06,96.232941,96.315842,94.641219,95.337595,5803800,ABBV,18.389999,1.561,34.444134,66.343300,21.896980,2021-05-06 00:00:00+00:00
4,2021-05-07,95.959358,96.937605,95.304430,96.481640,6808200,ABBV,16.690001,1.577,34.627430,66.911224,22.287622,2021-05-07 00:00:00+00:00

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1256 entries, 0 to 1255
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             1256 non-null   datetime64[ns]
 1   Close            1256 non-null   float64
 2   High             1256 non-null   float64
 3   Low              1256 non-null   float64
 4   Open             1256 non-null   float64
 5   Volume           1256 non-null   int64
 6   ticker           1256 non-null   object
 7   vix              1256 non-null   float64
 8   tnx              1256 non-null   float64
 9   xlf              1256 non-null   float64
 10  xlk              1256 non-null   float64
 11  xle              1256 non-null   float64
 12  event_timestamp  1256 non-null   datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), datetime64[ns](1), float64(9), int64(1), object(1)
memory usage: 127.7+ KB

In [17]:
df3 = pd.read_parquet(r'C:\Users\gehlo\Desktop\ML\Stock_Agent\data\processed\features.parquet')
df3.head()

,Close,High,Low,Open,Volume,ticker,vix,tnx,xlf,xlk,...,return_20d,ma20,ma50,ma_ratio,volatility_20d,rsi_14,bb_width,volume_ma20,volume_ratio,created_timestamp
0,144.342194,144.603270,143.297846,144.187472,1456500,A,17.120001,1.415,33.743202,73.258484,...,0.035156,142.588915,135.093783,1.055481,0.007692,66.005632,0.049285,1997645.0,0.729109,2026-05-03 16:44:57.907201+00:00
1,143.723404,144.922459,143.559018,144.912795,1218500,A,16.330000,1.356,33.586765,73.798523,...,0.029079,142.791979,135.395771,1.054627,0.007810,58.916341,0.045688,2006780.0,0.607192,2026-05-03 16:44:57.907201+00:00
2,144.042435,144.380871,142.959399,143.442893,1733600,A,17.010000,1.297,33.697182,73.190987,...,0.038762,143.060728,135.748370,1.053867,0.007544,64.367081,0.037209,2009420.0,0.862737,2026-05-03 16:44:57.907201+00:00
3,144.013458,144.874091,143.375258,144.400262,2169800,A,18.450001,1.300,33.237095,72.467773,...,0.015014,143.167236,136.052683,1.052293,0.005650,61.434584,0.036789,1976790.0,1.097638,2026-05-03 16:44:57.907201+00:00
4,142.708038,143.085163,142.098831,142.785399,1835100,A,22.500000,1.181,32.307709,71.469696,...,0.019061,143.300700,136.349622,1.050980,0.005196,49.110989,0.030718,1907510.0,0.962040,2026-05-03 16:44:57.907201+00:00

In [19]:
"event_timestamp" in df3.columns

True

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 601480 entries, 0 to 601479
Data columns (total 23 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Close            601480 non-null  float64
 1   High             601480 non-null  float64
 2   Low              601480 non-null  float64
 3   Open             601480 non-null  float64
 4   Volume           601480 non-null  int64
 5   ticker           601480 non-null  object
 6   vix              601480 non-null  float64
 7   tnx              601480 non-null  float64
 8   xlf              601480 non-null  float64
 9   xlk              601480 non-null  float64
 10  xle              601480 non-null  float64
 11  event_timestamp  601480 non-null  datetime64[ns, UTC]
 12  return_1d        601480 non-null  float64
 13  return_5d        601480 non-null  float64
 14  return_20d       601480 non-null  float64
 15  ma20             601480 non-null  float64
 16  ma50             601480 non-null  float64
 17  ma_ratio         601480 non-null  float64
 18  volatility_20d   601480 non-null  float64
 19  rsi_14           601480 non-null  float64
 20  bb_width         601480 non-null  float64
 21  volume_ma20      601480 non-null  float64
 22  volume_ratio     601480 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(20), int64(1), object(1)
memory usage: 105.5+ MB